# Generated by Django 5.0.6 on 2024-05-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_intro_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.PositiveIntegerField(),
        ),
    ]
