# Generated by Django 5.0.6 on 2024-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_intro_project_app', '0002_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
